/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const EntryType = IDL.Variant({
  'expense' : IDL.Null,
  'saving' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CategoryBreakdown = IDL.Record({
  'total' : IDL.Float64,
  'category' : IDL.Text,
});
export const EntrySummary = IDL.Record({
  'totalSavings' : IDL.Float64,
  'totalExpenses' : IDL.Float64,
  'netBalance' : IDL.Float64,
});
export const Dashboard = IDL.Record({
  'categoryBreakdown' : IDL.Vec(CategoryBreakdown),
  'summary' : EntrySummary,
});
export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'entryType' : EntryType,
  'date' : Time,
  'note' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateEntry' : IDL.Func(
      [
        IDL.Opt(IDL.Nat),
        Time,
        EntryType,
        IDL.Float64,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboard' : IDL.Func([], [Dashboard], ['query']),
  'getEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const EntryType = IDL.Variant({ 'expense' : IDL.Null, 'saving' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CategoryBreakdown = IDL.Record({
    'total' : IDL.Float64,
    'category' : IDL.Text,
  });
  const EntrySummary = IDL.Record({
    'totalSavings' : IDL.Float64,
    'totalExpenses' : IDL.Float64,
    'netBalance' : IDL.Float64,
  });
  const Dashboard = IDL.Record({
    'categoryBreakdown' : IDL.Vec(CategoryBreakdown),
    'summary' : EntrySummary,
  });
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'entryType' : EntryType,
    'date' : Time,
    'note' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateEntry' : IDL.Func(
        [
          IDL.Opt(IDL.Nat),
          Time,
          EntryType,
          IDL.Float64,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboard' : IDL.Func([], [Dashboard], ['query']),
    'getEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };