/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CategoryBreakdown { 'total' : number, 'category' : string }
export interface Dashboard {
  'categoryBreakdown' : Array<CategoryBreakdown>,
  'summary' : EntrySummary,
}
export interface Entry {
  'id' : bigint,
  'entryType' : EntryType,
  'date' : Time,
  'note' : [] | [string],
  'category' : [] | [string],
  'amount' : number,
}
export interface EntrySummary {
  'totalSavings' : number,
  'totalExpenses' : number,
  'netBalance' : number,
}
export type EntryType = { 'expense' : null } |
  { 'saving' : null };
export interface SavingsGoal {
  'id' : bigint,
  'name' : string,
  'note' : [] | [string],
  'createdAt' : Time,
  'deadline' : [] | [Time],
  'lastModified' : Time,
  'targetAmount' : number,
  'currentAmount' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateEntry' : ActorMethod<
    [[] | [bigint], Time, EntryType, number, [] | [string], [] | [string]],
    bigint
  >,
  'addOrUpdateSavingsGoal' : ActorMethod<
    [[] | [bigint], string, number, number, [] | [Time], [] | [string]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'deleteSavingsGoal' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboard' : ActorMethod<[], Dashboard>,
  'getEntries' : ActorMethod<[], Array<Entry>>,
  'getSavingsGoals' : ActorMethod<[], Array<SavingsGoal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];